export enum Permission {
  // 1. System Admin Permissions (SYSTEM.*)
  SYSTEM_ALL = 'SYSTEM.*',
  USER_ALL = 'USER.*',
  ROLE_ALL = 'ROLE.*',
  PERMISSION_ALL = 'PERMISSION.*',
  SECURITY_ALL = 'SECURITY.*',
  CONFIGURATION_ALL = 'CONFIGURATION.*',
  AUDIT_ALL = 'AUDIT.*',

  // 2. Platform Admin Permissions
  APPLICATION_MANAGE = 'APPLICATION_MANAGE',
  MODULE_ENABLE = 'MODULE_ENABLE',
  FEATURE_CONFIGURE = 'FEATURE_CONFIGURE',
  WORKFLOW_CONFIGURE = 'WORKFLOW_CONFIGURE',
  NOTIFICATION_CONFIGURE = 'NOTIFICATION_CONFIGURE',

  // 3. Security Admin Permissions
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  PERMISSION_ASSIGN = 'PERMISSION_ASSIGN',
  ACCESS_POLICY_MANAGE = 'ACCESS_POLICY_MANAGE',
  LOGIN_POLICY_MANAGE = 'LOGIN_POLICY_MANAGE',
  AUDIT_VIEW = 'AUDIT_VIEW',

  // 4. Organization Admin Permissions
  ORG_VIEW = 'ORG_VIEW',
  ORG_UPDATE = 'ORG_UPDATE',
  LOCATION_MANAGE = 'LOCATION_MANAGE',
  DEPARTMENT_MANAGE = 'DEPARTMENT_MANAGE',
  EMPLOYEE_STRUCTURE_MANAGE = 'EMPLOYEE_STRUCTURE_MANAGE',

  // 5. HR Admin Permissions
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE = 'EMPLOYEE_DELETE',
  EMPLOYEE_READ = 'EMPLOYEE_READ',
  ATTENDANCE_MANAGE = 'ATTENDANCE_MANAGE',
  LEAVE_MANAGE = 'LEAVE_MANAGE',
  PAYROLL_VIEW = 'PAYROLL_VIEW',
  PERFORMANCE_MANAGE = 'PERFORMANCE_MANAGE',
  RECRUITMENT_MANAGE = 'RECRUITMENT_MANAGE',

  // 6. HR Specialist Permissions
  RECRUITMENT_VIEW = 'RECRUITMENT_VIEW',
  CANDIDATE_MANAGE = 'CANDIDATE_MANAGE',
  INTERVIEW_SCHEDULE = 'INTERVIEW_SCHEDULE',
  SALARY_REPORT_VIEW = 'SALARY_REPORT_VIEW',
  SHIFT_MANAGE = 'SHIFT_MANAGE',

  // 7. Department Head Permissions
  DEPARTMENT_ANALYTICS_VIEW = 'DEPARTMENT_ANALYTICS_VIEW',
  TEAM_PERFORMANCE_VIEW = 'TEAM_PERFORMANCE_VIEW',
  HEADCOUNT_VIEW = 'HEADCOUNT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',

  // 8. Business Manager Permissions
  TEAM_VIEW = 'TEAM_VIEW',
  TEAM_ANALYTICS = 'TEAM_ANALYTICS',
  APPROVE_LEAVE = 'APPROVE_LEAVE',
  APPROVE_REQUESTS = 'APPROVE_REQUESTS',
  PERFORMANCE_REVIEW = 'PERFORMANCE_REVIEW',

  // 9. Team Lead Permissions
  TASK_TRACK = 'TASK_TRACK',
  ATTENDANCE_VIEW = 'ATTENDANCE_VIEW',
  PRODUCTIVITY_VIEW = 'PRODUCTIVITY_VIEW',
  FEEDBACK_CREATE = 'FEEDBACK_CREATE',

  // 10. Employee Self Service Permissions
  PROFILE_VIEW = 'PROFILE_VIEW',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  PAYSLIP_VIEW = 'PAYSLIP_VIEW',
  PERFORMANCE_VIEW = 'PERFORMANCE_VIEW',

  // 11. Analyst Permissions
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  REPORT_CREATE = 'REPORT_CREATE',
  DATA_EXPORT = 'DATA_EXPORT',
  TREND_ANALYSIS = 'TREND_ANALYSIS',

  // 12. Auditor Permissions
  AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
  ACCESS_HISTORY_VIEW = 'ACCESS_HISTORY_VIEW',
  REPORT_VIEW = 'REPORT_VIEW',

  // 13. Viewer Permissions
  CHART_VIEW = 'CHART_VIEW',

  // Legacy Permission Aliases
  USERS_READ = 'USER.*',
  USERS_CREATE = 'USER.*',
  USERS_UPDATE = 'USER.*',
  USERS_DELETE = 'USER.*',
  ROLES_MANAGE = 'ROLE_CREATE',
  SYSTEM_CONFIG = 'CONFIGURATION_ALL',
  EMPLOYEE_MANAGE = 'EMPLOYEE_CREATE',
  EMPLOYEE_SELF = 'PROFILE_VIEW',
  ATTENDANCE_CLOCK = 'ATTENDANCE_VIEW',
  ATTENDANCE_READ_SELF = 'ATTENDANCE_VIEW',
  ATTENDANCE_READ_TEAM = 'ATTENDANCE_VIEW',
  ANALYTICS_VIEW_ALL = 'DASHBOARD_VIEW',
  ANALYTICS_VIEW_TEAM = 'TEAM_ANALYTICS',
  REPORTS_EXPORT = 'REPORT_EXPORT',
  PERFORMANCE_READ_SELF = 'PERFORMANCE_VIEW',
  PERFORMANCE_READ_TEAM = 'TEAM_PERFORMANCE_VIEW'
}
